import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";
import WeatherToolbar from "@/components/layout/weather-toolbar";
import { getDictionary, Locale } from "@/lib/dictionaries";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: Promise<{ lang: string }>;
  }>
) {
  const params = await props.params;
  const lang = params.lang as Locale;
  const dictionary = await getDictionary(lang);
  const googlePlacesApiKey = process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY;

  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {googlePlacesApiKey ? (
          <Script
            src={`https://maps.googleapis.com/maps/api/js?key=${googlePlacesApiKey}&libraries=places`}
            strategy="beforeInteractive"
          />
        ) : null}
      </head>
      <body className="min-h-[100dvh] flex flex-col pt-[109px] bg-gray-50">
        <Navbar dictionary={dictionary.footer} currentLang={lang} />
        <WeatherToolbar />
        <main className="flex-1 flex flex-col relative">{props.children}</main>
        <Footer dictionary={dictionary.footer} currentLang={lang} />
      </body>
    </html>
  );
}
